// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/models/shared"
	"net/http"
)

type GetAllDesignsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Other errors
	ErrorResp *shared.ErrorResp
	// Success - designs loaded with success. Empty array if org has no designs.
	GetAllDesignsRes *shared.GetAllDesignsRes
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetAllDesignsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAllDesignsResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetAllDesignsResponse) GetGetAllDesignsRes() *shared.GetAllDesignsRes {
	if g == nil {
		return nil
	}
	return g.GetAllDesignsRes
}

func (g *GetAllDesignsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAllDesignsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
