// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/models/shared"
	"net/http"
)

type GetConsumerDesignRequest struct {
	Application string `pathParam:"style=simple,explode=false,name=application"`
	ConsumerID  string `pathParam:"style=simple,explode=false,name=consumerId"`
}

func (g *GetConsumerDesignRequest) GetApplication() string {
	if g == nil {
		return ""
	}
	return g.Application
}

func (g *GetConsumerDesignRequest) GetConsumerID() string {
	if g == nil {
		return ""
	}
	return g.ConsumerID
}

type GetConsumerDesignResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Validation Errors
	ErrorResp *shared.ErrorResp
	// Success - design loaded with success.
	GetDesignRes *shared.GetDesignRes
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetConsumerDesignResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetConsumerDesignResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetConsumerDesignResponse) GetGetDesignRes() *shared.GetDesignRes {
	if g == nil {
		return nil
	}
	return g.GetDesignRes
}

func (g *GetConsumerDesignResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetConsumerDesignResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
