// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/models/shared"
	"net/http"
)

type GetThemeFromDesignRequest struct {
	DesignID string `pathParam:"style=simple,explode=false,name=designId"`
	// Organization id of the user
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
	// Type of theme to be parsed and returned
	Theme shared.Theme `queryParam:"style=form,explode=true,name=theme"`
}

func (g *GetThemeFromDesignRequest) GetDesignID() string {
	if g == nil {
		return ""
	}
	return g.DesignID
}

func (g *GetThemeFromDesignRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

func (g *GetThemeFromDesignRequest) GetTheme() shared.Theme {
	if g == nil {
		return shared.Theme("")
	}
	return g.Theme
}

type GetThemeFromDesignResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Validation Errors
	ErrorResp *shared.ErrorResp
	// Success - design parsed with success.
	ParseThemeFromDesignResp *shared.ParseThemeFromDesignResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetThemeFromDesignResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetThemeFromDesignResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetThemeFromDesignResponse) GetParseThemeFromDesignResp() *shared.ParseThemeFromDesignResp {
	if g == nil {
		return nil
	}
	return g.ParseThemeFromDesignResp
}

func (g *GetThemeFromDesignResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetThemeFromDesignResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
