// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/models/shared"
	"net/http"
)

type UpdateDesignRequest struct {
	// Design payload
	UpdateDesignReq shared.UpdateDesignReq `request:"mediaType=application/json"`
	// Id of the design
	DesignID string `pathParam:"style=simple,explode=false,name=designId"`
}

func (o *UpdateDesignRequest) GetUpdateDesignReq() shared.UpdateDesignReq {
	if o == nil {
		return shared.UpdateDesignReq{}
	}
	return o.UpdateDesignReq
}

func (o *UpdateDesignRequest) GetDesignID() string {
	if o == nil {
		return ""
	}
	return o.DesignID
}

type UpdateDesignResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Validation Errors
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateDesignResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateDesignResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *UpdateDesignResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateDesignResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
