// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/models/shared"
	"net/http"
)

type UploadFileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Validation Errors
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success - upload with success.
	UploadFileRes *shared.UploadFileRes
}

func (u *UploadFileResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UploadFileResponse) GetErrorResp() *shared.ErrorResp {
	if u == nil {
		return nil
	}
	return u.ErrorResp
}

func (u *UploadFileResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UploadFileResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UploadFileResponse) GetUploadFileRes() *shared.UploadFileRes {
	if u == nil {
		return nil
	}
	return u.UploadFileRes
}
