openapi: 3.0.0
info:
  title: Journey API
  description: API to configure journeys
  version: 1.0.0
security:
- EpilotAuth: []
paths:
  /v1/journey/organization/{id}:
    get:
      operationId: getJourneysByOrgId
      summary: getJourneysByOrgId
      description: Get all journeys by organization id
      tags:
      - Journeys
      parameters:
      - name: id
        in: path
        description: Organization ID
        required: true
        schema:
          type: string
          example: '123'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetJourneysResponse'
  /v1/journey/configuration/{id}:
    get:
      x-speakeasy-entity-operation: Journey#get
      operationId: getJourney
      summary: getJourney
      description: Get journey by id
      security: []
      tags:
      - Journeys
      parameters:
      - name: id
        in: path
        x-speakeasy-match: journeyId
        description: Journey ID
        required: true
        schema:
          type: string
          format: uuid
          example: 509cdffe-424f-457a-95c2-9708c304ce77
      - name: source
        in: query
        x-speakeasy-ignore: true
        description: What source ID. Journey or Entity ID
        required: false
        schema:
          type: string
      - name: orgId
        in: query
        x-speakeasy-match: organizationId
        description: Organization ID
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JourneyResponse'
    delete:
      x-speakeasy-entity-operation: Journey#delete
      operationId: removeJourney
      summary: removeJourney
      description: Remove journey by id
      tags:
      - Journeys
      parameters:
      - name: id
        in: path
        description: Journey ID
        x-speakeasy-match: journeyId
        required: true
        schema:
          type: string
          format: uuid
          example: 509cdffe-424f-457a-95c2-9708c304ce77
      responses:
        '200':
          description: Success
          content: {}
  /v1/journey/configuration:
    post:
      x-speakeasy-entity-operation: Journey#create
      operationId: createJourney
      summary: createJourney
      description: Create a Journey
      tags:
      - Journeys
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JourneyCreationRequest'
        description: Payload
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JourneyResponse'
    put:
      x-speakeasy-entity-operation: Journey#update
      operationId: updateJourney
      summary: updateJourney
      description: Update a Journey
      tags:
      - Journeys
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JourneyCreationRequest'
        description: Payload
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JourneyResponse'
    patch:
      operationId: patchUpdateJourney
      summary: patchUpdateJourney
      description: Update a Journey (partially / patch). Support for nested properties updates (e.g. "property[0].name").
      tags:
      - Journeys
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchUpdateJourneyRequest'
            example:
              journeyId: 509cdffe-424f-457a-95c2-9708c304ce77
              name: New Journey Name
              steps[0].uischema.elements[0].products:
              - '123456'
              - '654321'
        description: Payload
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JourneyResponse'
  /v1/journey/configuration/search:
    post:
      operationId: searchJourneys
      summary: searchJourneys
      description: Search Journeys
      tags:
      - Journeys
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchJourneysQueryRequest'
        description: Payload
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchJourneysResponse'
components:
  schemas:
    GetJourneysResponse:
      type: object
    JourneyResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/JourneyCreationRequest'
    PatchUpdateJourneyRequest:
      type: object
      properties:
        journeyId:
          type: string
          format: uuid
          example: 509cdffe-424f-457a-95c2-9708c304ce77
      additionalProperties: true
      description: |
        Patch request to update a journey (journey id is required) Support for nested properties (e.g. steps[0].uischema.elements[0].products) is supported.
      required:
      - journeyId
    JourneyCreationRequest:
      x-speakeasy-entity: Journey
      type: object
      properties:
        journeyId:
          type: string
        organizationId:
          type: string
        brandId:
          type: string
        name:
          type: string
        steps:
          type: array
          items:
            type: object
            additionalProperties: false
            properties:
              showStepName:
                type: boolean
                nullable: true
              title:
                type: string
                nullable: true
              subTitle:
                type: string
                nullable: true
              showStepSubtitle:
                type: boolean
                nullable: true
              showStepper:
                type: boolean
                nullable: true
              showStepperLabels:
                type: boolean
                nullable: true
              hideNextButton:
                type: boolean
                nullable: true
              name:
                type: string
              stepId:
                type: string
              schema: {}
              uischema: {}
            required:
            - name
            - schema
            - uischema
        design:
          type: object
          properties:
            logoUrl:
              type: string
              nullable: true
            theme:
              type: object
              additionalProperties: {}
          required:
          - theme
          additionalProperties: false
        rules:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum:
                - inject
                - injectWithKey
              sourceType:
                type: string
                enum:
                - journey
                - step
                - block
              source:
                type: string
              target:
                type: string
            required:
            - type
            - sourceType
            - source
            - target
            additionalProperties: false
        logics:
          type: array
          items:
            type: object
            properties:
              autoGeneratedId:
                type: string
              conditions:
                type: array
                items:
                  type: string
              actions:
                type: array
                items:
                  type: string
            required:
            - conditions
            - actions
            additionalProperties: false
        settings:
          type: object
          properties:
            embedOptions:
              type: object
              properties:
                mode:
                  type: string
                  enum:
                  - full-screen
                  - inline
                lang:
                  type: string
                  enum:
                  - de
                  - en
                  - fr
                width:
                  type: string
                topBar:
                  type: boolean
                scrollToTop:
                  type: boolean
                button:
                  type: object
                  properties:
                    text:
                      type: string
                      nullable: true
                    align:
                      type: string
                      enum:
                      - left
                      - center
                      - right
            safeModeAutomation:
              type: boolean
            designId:
              type: string
            templateId:
              type: string
            entityId:
              type: string
              nullable: true
            mappingsAutomationId:
              type: string
            targetedCustomer:
              type: string
            description:
              type: string
              nullable: true
            organizationSettings:
              type: object
              additionalProperties:
                type: boolean
              nullable: true
            publicToken:
              type: string
              nullable: true
            runtimeEntities:
              type: array
              items:
                type: string
                enum:
                - ORDER
                - OPPORTUNITY
            entityTags:
              type: array
              items:
                type: string
          required:
          - designId
          additionalProperties: false
        createdBy:
          type: string
      required:
      - organizationId
      - brandId
      - name
      - steps
      additionalProperties: false
    SearchJourneysQueryRequest:
      type: object
      properties:
        q:
          type: string
          description: |
            Lucene query syntax
            See https://lucene.apache.org/core/2_9_4/queryparsersyntax.html ; https://www.elastic.co/guide/en/kibana/current/lucene-query.html
          example: _tags:*Flex*
          default: '*'
        from:
          type: integer
          description: |
            The offset of the first result to return.
            See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html
          example: 0
          default: 0
        size:
          type: integer
          description: |
            The maximum number of results to return.
            See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html
          example: 25
          default: 25
        sort:
          type: string
          description: |
            The sort order. Follows Lucene syntax.
          example: _created_at:desc
          default: _created_at:desc
    SearchJourneysResponse:
      type: object
      properties:
        hits:
          type: number
          description: |
            The total number of hits.
          example: 1
        results:
          type: array
          description: |
            The results.
          items:
            type: object
            properties:
              _id:
                type: string
                description: Journey Entity ID
                format: uuid
                example: e0f8f8f8-f8f8-f8f8-f8f8-f8f8f8f8f8f8
              _schema:
                type: string
                description: Entity Schema (journey always in this case)
                example: journey
              _title:
                type: string
                description: Journey Entity Title
                example: Journey Entity Title
              _org:
                type: string
                description: Organization ID
                example: '739224'
              _created_at:
                type: string
                format: date-time
                example: '2020-01-01T00:00:00.000Z'
              _updated_at:
                type: string
                format: date-time
                example: '2020-01-01T00:00:00.000Z'
              _tags:
                type: array
                items:
                  type: string
                  example: Flex
              journey_name:
                type: string
                description: Journey Name
                example: Journey Name
              journey_id:
                type: string
                format: uuid
                description: Journey config ID
                example: de7df470-253e-11ed-9174-116b8a718c0a
              journey_type:
                type: string
                description: Journey Template
                example: Sales template
              design:
                type: string
                description: Journey Design Name
                example: Design EPILOT
              created_by:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: User ID
                      example: '12345'
              journey_version:
                type: string
                description: Journey Version
                enum:
                - Flex
                - Widget
  securitySchemes:
    EpilotAuth:
      type: http
      scheme: bearer
      description: Authorization header with epilot OAuth2 bearer token
      bearerFormat: JWT
servers:
- url: https://journey-config.sls.epilot.io

