resource "epilot-designbuilder_design" "my_design" {
  brand_id     = "{ \"see\": \"documentation\" }"
  brand_name   = "...my_brand_name..."
  custom_theme = "{ \"see\": \"documentation\" }"
  design_tokens = {
    accent_color               = "...my_accent_color..."
    button_border_radius       = 7.98
    button_ghost_bg            = "...my_button_ghost_bg..."
    button_ghost_hover_bg      = "...my_button_ghost_hover_bg..."
    button_ghost_hover_text    = "...my_button_ghost_hover_text..."
    button_ghost_text          = "...my_button_ghost_text..."
    button_height              = 2.73
    button_outlined_border     = "...my_button_outlined_border..."
    button_outlined_hover_bg   = "...my_button_outlined_hover_bg..."
    button_outlined_hover_text = "...my_button_outlined_hover_text..."
    button_outlined_text       = "...my_button_outlined_text..."
    button_primary_bg          = "...my_button_primary_bg..."
    button_primary_hover_bg    = "...my_button_primary_hover_bg..."
    button_primary_hover_text  = "...my_button_primary_hover_text..."
    button_primary_text        = "...my_button_primary_text..."
    card_background            = "...my_card_background..."
    card_border_color          = "...my_card_border_color..."
    card_variant               = "outlined"
    cashback                   = "...my_cashback..."
    checkbox_label_color       = "...my_checkbox_label_color..."
    checkbox_unchecked_color   = "...my_checkbox_unchecked_color..."
    chip_background            = "...my_chip_background..."
    chip_hover_background      = "...my_chip_hover_background..."
    chip_hover_text_color      = "...my_chip_hover_text_color..."
    chip_text_color            = "...my_chip_text_color..."
    coupon                     = "...my_coupon..."
    custom_css                 = "...my_custom_css..."
    datepicker_border_radius   = 2.43
    datepicker_selected_bg     = "...my_datepicker_selected_bg..."
    datepicker_selected_color  = "...my_datepicker_selected_color..."
    divider_color              = "...my_divider_color..."
    dropdown_hover_bg          = "...my_dropdown_hover_bg..."
    dropdown_hover_text        = "...my_dropdown_hover_text..."
    dropdown_selected_bg       = "...my_dropdown_selected_bg..."
    dropdown_selected_text     = "...my_dropdown_selected_text..."
    font_size_scale            = "lg"
    input_background           = "...my_input_background..."
    input_border_color         = "...my_input_border_color..."
    input_border_radius        = 8.41
    input_height               = 6.13
    input_label_color          = "...my_input_label_color..."
    input_text_color           = "...my_input_text_color..."
    input_variant              = "underlined"
    link_color                 = "...my_link_color..."
    link_hover_color           = "...my_link_hover_color..."
    logo_size                  = 5.4
    outline_color              = "...my_outline_color..."
    radio_label_color          = "...my_radio_label_color..."
    radio_unchecked_color      = "...my_radio_unchecked_color..."
    summary_card_background    = "...my_summary_card_background..."
    switch_border_radius       = 4.63
    switch_unchecked_bg        = "...my_switch_unchecked_bg..."
    switch_unchecked_color     = "...my_switch_unchecked_color..."
    toggle_border_color        = "...my_toggle_border_color..."
    toggle_hover_bg            = "...my_toggle_hover_bg..."
    toggle_hover_text          = "...my_toggle_hover_text..."
    toggle_selected_bg         = "...my_toggle_selected_bg..."
    toggle_selected_text       = "...my_toggle_selected_text..."
    topbar_height              = 8.63
    topbar_logo_alignment      = "flex-end"
  }
  is_default = true
  manifest = [
    "..."
  ]
  style            = "{ \"see\": \"documentation\" }"
  style_name       = "...my_style_name..."
  use_custom_theme = false
  user = {
    emailaddress = "...my_emailaddress..."
    fullname     = "...my_fullname..."
    name         = "...my_name..."
    userid       = "...my_userid..."
  }
}