// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/pkg/utils"
)

type AddDesignResBrandIDType string

const (
	AddDesignResBrandIDTypeStr    AddDesignResBrandIDType = "str"
	AddDesignResBrandIDTypeNumber AddDesignResBrandIDType = "number"
)

type AddDesignResBrandID struct {
	Str    *string
	Number *float64

	Type AddDesignResBrandIDType
}

func CreateAddDesignResBrandIDStr(str string) AddDesignResBrandID {
	typ := AddDesignResBrandIDTypeStr

	return AddDesignResBrandID{
		Str:  &str,
		Type: typ,
	}
}

func CreateAddDesignResBrandIDNumber(number float64) AddDesignResBrandID {
	typ := AddDesignResBrandIDTypeNumber

	return AddDesignResBrandID{
		Number: &number,
		Type:   typ,
	}
}

func (u *AddDesignResBrandID) UnmarshalJSON(data []byte) error {

	str := new(string)
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = str
		u.Type = AddDesignResBrandIDTypeStr
		return nil
	}

	number := new(float64)
	if err := utils.UnmarshalJSON(data, &number, "", true, true); err == nil {
		u.Number = number
		u.Type = AddDesignResBrandIDTypeNumber
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u AddDesignResBrandID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type AddDesignResCustomTheme struct {
}

type AddDesignResStyle struct {
	Consumer   ConsumerData   `json:"consumer"`
	Logo       *LogoData      `json:"logo,omitempty"`
	Palette    PaletteData    `json:"palette"`
	Typography TypographyData `json:"typography"`
}

func (o *AddDesignResStyle) GetConsumer() ConsumerData {
	if o == nil {
		return ConsumerData{}
	}
	return o.Consumer
}

func (o *AddDesignResStyle) GetLogo() *LogoData {
	if o == nil {
		return nil
	}
	return o.Logo
}

func (o *AddDesignResStyle) GetPalette() PaletteData {
	if o == nil {
		return PaletteData{}
	}
	return o.Palette
}

func (o *AddDesignResStyle) GetTypography() TypographyData {
	if o == nil {
		return TypographyData{}
	}
	return o.Typography
}

type AddDesignResUser struct {
	Emailaddress *string `json:"emailaddress,omitempty"`
	Fullname     *string `json:"fullname,omitempty"`
	Name         *string `json:"name,omitempty"`
	Userid       *string `json:"userid,omitempty"`
}

func (o *AddDesignResUser) GetEmailaddress() *string {
	if o == nil {
		return nil
	}
	return o.Emailaddress
}

func (o *AddDesignResUser) GetFullname() *string {
	if o == nil {
		return nil
	}
	return o.Fullname
}

func (o *AddDesignResUser) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AddDesignResUser) GetUserid() *string {
	if o == nil {
		return nil
	}
	return o.Userid
}

type AddDesignResDesign struct {
	BrandID   *AddDesignResBrandID `json:"brand_id,omitempty"`
	BrandName *string              `json:"brand_name,omitempty"`
	// Creation date and time using ISO 8601 full-time format
	CreatedAt      *string                  `json:"created_at,omitempty"`
	CreatedBy      *string                  `json:"created_by,omitempty"`
	CustomTheme    *AddDesignResCustomTheme `json:"custom_theme,omitempty"`
	Edited         bool                     `json:"edited"`
	ID             *string                  `json:"id,omitempty"`
	LastModifiedAt *string                  `json:"last_modified_at,omitempty"`
	Style          AddDesignResStyle        `json:"style"`
	StyleName      string                   `json:"style_name"`
	UseCustomTheme *bool                    `json:"use_custom_theme,omitempty"`
	User           *AddDesignResUser        `json:"user,omitempty"`
}

func (o *AddDesignResDesign) GetBrandID() *AddDesignResBrandID {
	if o == nil {
		return nil
	}
	return o.BrandID
}

func (o *AddDesignResDesign) GetBrandName() *string {
	if o == nil {
		return nil
	}
	return o.BrandName
}

func (o *AddDesignResDesign) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *AddDesignResDesign) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *AddDesignResDesign) GetCustomTheme() *AddDesignResCustomTheme {
	if o == nil {
		return nil
	}
	return o.CustomTheme
}

func (o *AddDesignResDesign) GetEdited() bool {
	if o == nil {
		return false
	}
	return o.Edited
}

func (o *AddDesignResDesign) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddDesignResDesign) GetLastModifiedAt() *string {
	if o == nil {
		return nil
	}
	return o.LastModifiedAt
}

func (o *AddDesignResDesign) GetStyle() AddDesignResStyle {
	if o == nil {
		return AddDesignResStyle{}
	}
	return o.Style
}

func (o *AddDesignResDesign) GetStyleName() string {
	if o == nil {
		return ""
	}
	return o.StyleName
}

func (o *AddDesignResDesign) GetUseCustomTheme() *bool {
	if o == nil {
		return nil
	}
	return o.UseCustomTheme
}

func (o *AddDesignResDesign) GetUser() *AddDesignResUser {
	if o == nil {
		return nil
	}
	return o.User
}

type AddDesignRes struct {
	Design *AddDesignResDesign `json:"design,omitempty"`
}

func (o *AddDesignRes) GetDesign() *AddDesignResDesign {
	if o == nil {
		return nil
	}
	return o.Design
}
