// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/pkg/utils"
)

type UpdateDesignReqBrandIDType string

const (
	UpdateDesignReqBrandIDTypeStr    UpdateDesignReqBrandIDType = "str"
	UpdateDesignReqBrandIDTypeNumber UpdateDesignReqBrandIDType = "number"
)

type UpdateDesignReqBrandID struct {
	Str    *string
	Number *float64

	Type UpdateDesignReqBrandIDType
}

func CreateUpdateDesignReqBrandIDStr(str string) UpdateDesignReqBrandID {
	typ := UpdateDesignReqBrandIDTypeStr

	return UpdateDesignReqBrandID{
		Str:  &str,
		Type: typ,
	}
}

func CreateUpdateDesignReqBrandIDNumber(number float64) UpdateDesignReqBrandID {
	typ := UpdateDesignReqBrandIDTypeNumber

	return UpdateDesignReqBrandID{
		Number: &number,
		Type:   typ,
	}
}

func (u *UpdateDesignReqBrandID) UnmarshalJSON(data []byte) error {

	str := new(string)
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = str
		u.Type = UpdateDesignReqBrandIDTypeStr
		return nil
	}

	number := new(float64)
	if err := utils.UnmarshalJSON(data, &number, "", true, true); err == nil {
		u.Number = number
		u.Type = UpdateDesignReqBrandIDTypeNumber
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u UpdateDesignReqBrandID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type UpdateDesignReqCustomTheme struct {
}

type UpdateDesignReqStyle struct {
	Consumer   ConsumerData   `json:"consumer"`
	Logo       *LogoData      `json:"logo,omitempty"`
	Palette    PaletteData    `json:"palette"`
	Typography TypographyData `json:"typography"`
}

func (o *UpdateDesignReqStyle) GetConsumer() ConsumerData {
	if o == nil {
		return ConsumerData{}
	}
	return o.Consumer
}

func (o *UpdateDesignReqStyle) GetLogo() *LogoData {
	if o == nil {
		return nil
	}
	return o.Logo
}

func (o *UpdateDesignReqStyle) GetPalette() PaletteData {
	if o == nil {
		return PaletteData{}
	}
	return o.Palette
}

func (o *UpdateDesignReqStyle) GetTypography() TypographyData {
	if o == nil {
		return TypographyData{}
	}
	return o.Typography
}

type UpdateDesignReqUser struct {
	Emailaddress *string `json:"emailaddress,omitempty"`
	Fullname     *string `json:"fullname,omitempty"`
	Name         *string `json:"name,omitempty"`
	Userid       *string `json:"userid,omitempty"`
}

func (o *UpdateDesignReqUser) GetEmailaddress() *string {
	if o == nil {
		return nil
	}
	return o.Emailaddress
}

func (o *UpdateDesignReqUser) GetFullname() *string {
	if o == nil {
		return nil
	}
	return o.Fullname
}

func (o *UpdateDesignReqUser) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateDesignReqUser) GetUserid() *string {
	if o == nil {
		return nil
	}
	return o.Userid
}

type UpdateDesignReqDesign struct {
	BrandID   *UpdateDesignReqBrandID `json:"brand_id,omitempty"`
	BrandName *string                 `json:"brand_name,omitempty"`
	// Creation date and time using ISO 8601 full-time format
	CreatedAt      *string                     `json:"created_at,omitempty"`
	CreatedBy      *string                     `json:"created_by,omitempty"`
	CustomTheme    *UpdateDesignReqCustomTheme `json:"custom_theme,omitempty"`
	Edited         bool                        `json:"edited"`
	ID             *string                     `json:"id,omitempty"`
	LastModifiedAt *string                     `json:"last_modified_at,omitempty"`
	Style          UpdateDesignReqStyle        `json:"style"`
	StyleName      string                      `json:"style_name"`
	UseCustomTheme *bool                       `json:"use_custom_theme,omitempty"`
	User           *UpdateDesignReqUser        `json:"user,omitempty"`
}

func (o *UpdateDesignReqDesign) GetBrandID() *UpdateDesignReqBrandID {
	if o == nil {
		return nil
	}
	return o.BrandID
}

func (o *UpdateDesignReqDesign) GetBrandName() *string {
	if o == nil {
		return nil
	}
	return o.BrandName
}

func (o *UpdateDesignReqDesign) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *UpdateDesignReqDesign) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *UpdateDesignReqDesign) GetCustomTheme() *UpdateDesignReqCustomTheme {
	if o == nil {
		return nil
	}
	return o.CustomTheme
}

func (o *UpdateDesignReqDesign) GetEdited() bool {
	if o == nil {
		return false
	}
	return o.Edited
}

func (o *UpdateDesignReqDesign) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UpdateDesignReqDesign) GetLastModifiedAt() *string {
	if o == nil {
		return nil
	}
	return o.LastModifiedAt
}

func (o *UpdateDesignReqDesign) GetStyle() UpdateDesignReqStyle {
	if o == nil {
		return UpdateDesignReqStyle{}
	}
	return o.Style
}

func (o *UpdateDesignReqDesign) GetStyleName() string {
	if o == nil {
		return ""
	}
	return o.StyleName
}

func (o *UpdateDesignReqDesign) GetUseCustomTheme() *bool {
	if o == nil {
		return nil
	}
	return o.UseCustomTheme
}

func (o *UpdateDesignReqDesign) GetUser() *UpdateDesignReqUser {
	if o == nil {
		return nil
	}
	return o.User
}

type UpdateDesignReq struct {
	Design UpdateDesignReqDesign `json:"design"`
}

func (o *UpdateDesignReq) GetDesign() UpdateDesignReqDesign {
	if o == nil {
		return UpdateDesignReqDesign{}
	}
	return o.Design
}
