// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AddConsumerReq struct {
	// Id of the design
	ConsumerID   string  `json:"consumer_id"`
	ConsumerName string  `json:"consumer_name"`
	ShouldDelete *string `json:"should_delete,omitempty"`
}

func (a *AddConsumerReq) GetConsumerID() string {
	if a == nil {
		return ""
	}
	return a.ConsumerID
}

func (a *AddConsumerReq) GetConsumerName() string {
	if a == nil {
		return ""
	}
	return a.ConsumerName
}

func (a *AddConsumerReq) GetShouldDelete() *string {
	if a == nil {
		return nil
	}
	return a.ShouldDelete
}
