// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type User struct {
	Emailaddress *string `json:"emailaddress,omitempty"`
	Fullname     *string `json:"fullname,omitempty"`
	Name         *string `json:"name,omitempty"`
	Userid       *string `json:"userid,omitempty"`
}

func (o *User) GetEmailaddress() *string {
	if o == nil {
		return nil
	}
	return o.Emailaddress
}

func (o *User) GetFullname() *string {
	if o == nil {
		return nil
	}
	return o.Fullname
}

func (o *User) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *User) GetUserid() *string {
	if o == nil {
		return nil
	}
	return o.Userid
}

type Design struct {
	BrandID        any     `json:"brand_id,omitempty"`
	BrandName      *string `json:"brand_name,omitempty"`
	Cashback       *string `json:"cashback,omitempty"`
	Coupon         *string `json:"coupon,omitempty"`
	CustomCSS      *string `json:"custom_css,omitempty"`
	CustomTheme    *string `json:"custom_theme,omitempty"`
	IsDefault      *bool   `json:"is_default,omitempty"`
	Style          any     `json:"style"`
	StyleName      string  `json:"style_name"`
	UseCustomTheme *bool   `json:"use_custom_theme,omitempty"`
	User           *User   `json:"user,omitempty"`
}

func (o *Design) GetBrandID() any {
	if o == nil {
		return nil
	}
	return o.BrandID
}

func (o *Design) GetBrandName() *string {
	if o == nil {
		return nil
	}
	return o.BrandName
}

func (o *Design) GetCashback() *string {
	if o == nil {
		return nil
	}
	return o.Cashback
}

func (o *Design) GetCoupon() *string {
	if o == nil {
		return nil
	}
	return o.Coupon
}

func (o *Design) GetCustomCSS() *string {
	if o == nil {
		return nil
	}
	return o.CustomCSS
}

func (o *Design) GetCustomTheme() *string {
	if o == nil {
		return nil
	}
	return o.CustomTheme
}

func (o *Design) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

func (o *Design) GetStyle() any {
	if o == nil {
		return nil
	}
	return o.Style
}

func (o *Design) GetStyleName() string {
	if o == nil {
		return ""
	}
	return o.StyleName
}

func (o *Design) GetUseCustomTheme() *bool {
	if o == nil {
		return nil
	}
	return o.UseCustomTheme
}

func (o *Design) GetUser() *User {
	if o == nil {
		return nil
	}
	return o.User
}

type AddDesignReq struct {
	Design Design `json:"design"`
}

func (o *AddDesignReq) GetDesign() Design {
	if o == nil {
		return Design{}
	}
	return o.Design
}
