// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetAllDesignsResDesignTokens struct {
	Cashback  *string `json:"cashback,omitempty"`
	Coupon    *string `json:"coupon,omitempty"`
	CustomCSS *string `json:"custom_css,omitempty"`
}

func (g *GetAllDesignsResDesignTokens) GetCashback() *string {
	if g == nil {
		return nil
	}
	return g.Cashback
}

func (g *GetAllDesignsResDesignTokens) GetCoupon() *string {
	if g == nil {
		return nil
	}
	return g.Coupon
}

func (g *GetAllDesignsResDesignTokens) GetCustomCSS() *string {
	if g == nil {
		return nil
	}
	return g.CustomCSS
}

type GetAllDesignsResUser struct {
	Emailaddress *string `json:"emailaddress,omitempty"`
	Fullname     *string `json:"fullname,omitempty"`
	Name         *string `json:"name,omitempty"`
	Userid       *string `json:"userid,omitempty"`
}

func (g *GetAllDesignsResUser) GetEmailaddress() *string {
	if g == nil {
		return nil
	}
	return g.Emailaddress
}

func (g *GetAllDesignsResUser) GetFullname() *string {
	if g == nil {
		return nil
	}
	return g.Fullname
}

func (g *GetAllDesignsResUser) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *GetAllDesignsResUser) GetUserid() *string {
	if g == nil {
		return nil
	}
	return g.Userid
}

type Designs struct {
	BrandID   any     `json:"brand_id,omitempty"`
	BrandName *string `json:"brand_name,omitempty"`
	// Creation date and time
	CreatedAt      *string                       `json:"created_at,omitempty"`
	CreatedBy      *string                       `json:"created_by,omitempty"`
	CustomTheme    any                           `json:"custom_theme,omitempty"`
	DesignTokens   *GetAllDesignsResDesignTokens `json:"design_tokens,omitempty"`
	Edited         bool                          `json:"edited"`
	ID             *string                       `json:"id,omitempty"`
	IsDefault      *bool                         `json:"is_default,omitempty"`
	LastModifiedAt *string                       `json:"last_modified_at,omitempty"`
	Style          any                           `json:"style"`
	StyleName      string                        `json:"style_name"`
	UseCustomTheme *bool                         `json:"use_custom_theme,omitempty"`
	User           *GetAllDesignsResUser         `json:"user,omitempty"`
}

func (d *Designs) GetBrandID() any {
	if d == nil {
		return nil
	}
	return d.BrandID
}

func (d *Designs) GetBrandName() *string {
	if d == nil {
		return nil
	}
	return d.BrandName
}

func (d *Designs) GetCreatedAt() *string {
	if d == nil {
		return nil
	}
	return d.CreatedAt
}

func (d *Designs) GetCreatedBy() *string {
	if d == nil {
		return nil
	}
	return d.CreatedBy
}

func (d *Designs) GetCustomTheme() any {
	if d == nil {
		return nil
	}
	return d.CustomTheme
}

func (d *Designs) GetDesignTokens() *GetAllDesignsResDesignTokens {
	if d == nil {
		return nil
	}
	return d.DesignTokens
}

func (d *Designs) GetEdited() bool {
	if d == nil {
		return false
	}
	return d.Edited
}

func (d *Designs) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *Designs) GetIsDefault() *bool {
	if d == nil {
		return nil
	}
	return d.IsDefault
}

func (d *Designs) GetLastModifiedAt() *string {
	if d == nil {
		return nil
	}
	return d.LastModifiedAt
}

func (d *Designs) GetStyle() any {
	if d == nil {
		return nil
	}
	return d.Style
}

func (d *Designs) GetStyleName() string {
	if d == nil {
		return ""
	}
	return d.StyleName
}

func (d *Designs) GetUseCustomTheme() *bool {
	if d == nil {
		return nil
	}
	return d.UseCustomTheme
}

func (d *Designs) GetUser() *GetAllDesignsResUser {
	if d == nil {
		return nil
	}
	return d.User
}

type GetAllDesignsRes struct {
	Designs []Designs `json:"designs,omitempty"`
}

func (g *GetAllDesignsRes) GetDesigns() []Designs {
	if g == nil {
		return nil
	}
	return g.Designs
}
