// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetBrandsRes struct {
	Brands []BrandItem `json:"brands,omitempty"`
}

func (o *GetBrandsRes) GetBrands() []BrandItem {
	if o == nil {
		return nil
	}
	return o.Brands
}
