// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/internal/utils"
	"time"
)

type GetDesignResStyle struct {
	Consumer   ConsumerData   `json:"consumer"`
	Logo       *LogoData      `json:"logo,omitempty"`
	Palette    PaletteData    `json:"palette"`
	Shape      *ShapeData     `json:"shape,omitempty"`
	Typography TypographyData `json:"typography"`
}

func (o *GetDesignResStyle) GetConsumer() ConsumerData {
	if o == nil {
		return ConsumerData{}
	}
	return o.Consumer
}

func (o *GetDesignResStyle) GetLogo() *LogoData {
	if o == nil {
		return nil
	}
	return o.Logo
}

func (o *GetDesignResStyle) GetPalette() PaletteData {
	if o == nil {
		return PaletteData{}
	}
	return o.Palette
}

func (o *GetDesignResStyle) GetShape() *ShapeData {
	if o == nil {
		return nil
	}
	return o.Shape
}

func (o *GetDesignResStyle) GetTypography() TypographyData {
	if o == nil {
		return TypographyData{}
	}
	return o.Typography
}

type GetDesignResUser struct {
	Emailaddress *string `json:"emailaddress,omitempty"`
	Fullname     *string `json:"fullname,omitempty"`
	Name         *string `json:"name,omitempty"`
	Userid       *string `json:"userid,omitempty"`
}

func (o *GetDesignResUser) GetEmailaddress() *string {
	if o == nil {
		return nil
	}
	return o.Emailaddress
}

func (o *GetDesignResUser) GetFullname() *string {
	if o == nil {
		return nil
	}
	return o.Fullname
}

func (o *GetDesignResUser) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GetDesignResUser) GetUserid() *string {
	if o == nil {
		return nil
	}
	return o.Userid
}

type GetDesignResDesign struct {
	BrandID   *string `json:"brand_id,omitempty"`
	BrandName *string `json:"brand_name,omitempty"`
	Cashback  *string `json:"cashback,omitempty"`
	Coupon    *string `json:"coupon,omitempty"`
	// Creation date and time using ISO 8601 full-time format
	CreatedAt      *time.Time        `json:"created_at,omitempty"`
	CreatedBy      *string           `json:"created_by,omitempty"`
	CustomCSS      *string           `json:"custom_css,omitempty"`
	CustomTheme    *string           `json:"custom_theme,omitempty"`
	Edited         bool              `json:"edited"`
	ID             *string           `json:"id,omitempty"`
	IsDefault      *bool             `json:"is_default,omitempty"`
	LastModifiedAt *time.Time        `json:"last_modified_at,omitempty"`
	Style          GetDesignResStyle `json:"style"`
	StyleName      string            `json:"style_name"`
	UseCustomTheme *bool             `json:"use_custom_theme,omitempty"`
	User           *GetDesignResUser `json:"user,omitempty"`
}

func (g GetDesignResDesign) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDesignResDesign) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetDesignResDesign) GetBrandID() *string {
	if o == nil {
		return nil
	}
	return o.BrandID
}

func (o *GetDesignResDesign) GetBrandName() *string {
	if o == nil {
		return nil
	}
	return o.BrandName
}

func (o *GetDesignResDesign) GetCashback() *string {
	if o == nil {
		return nil
	}
	return o.Cashback
}

func (o *GetDesignResDesign) GetCoupon() *string {
	if o == nil {
		return nil
	}
	return o.Coupon
}

func (o *GetDesignResDesign) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *GetDesignResDesign) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *GetDesignResDesign) GetCustomCSS() *string {
	if o == nil {
		return nil
	}
	return o.CustomCSS
}

func (o *GetDesignResDesign) GetCustomTheme() *string {
	if o == nil {
		return nil
	}
	return o.CustomTheme
}

func (o *GetDesignResDesign) GetEdited() bool {
	if o == nil {
		return false
	}
	return o.Edited
}

func (o *GetDesignResDesign) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *GetDesignResDesign) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

func (o *GetDesignResDesign) GetLastModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastModifiedAt
}

func (o *GetDesignResDesign) GetStyle() GetDesignResStyle {
	if o == nil {
		return GetDesignResStyle{}
	}
	return o.Style
}

func (o *GetDesignResDesign) GetStyleName() string {
	if o == nil {
		return ""
	}
	return o.StyleName
}

func (o *GetDesignResDesign) GetUseCustomTheme() *bool {
	if o == nil {
		return nil
	}
	return o.UseCustomTheme
}

func (o *GetDesignResDesign) GetUser() *GetDesignResUser {
	if o == nil {
		return nil
	}
	return o.User
}

type GetDesignRes struct {
	Design *GetDesignResDesign `json:"design,omitempty"`
}

func (o *GetDesignRes) GetDesign() *GetDesignResDesign {
	if o == nil {
		return nil
	}
	return o.Design
}
