// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetDesignResDesignTokens struct {
	Cashback  *string `json:"cashback,omitempty"`
	Coupon    *string `json:"coupon,omitempty"`
	CustomCSS *string `json:"custom_css,omitempty"`
}

func (o *GetDesignResDesignTokens) GetCashback() *string {
	if o == nil {
		return nil
	}
	return o.Cashback
}

func (o *GetDesignResDesignTokens) GetCoupon() *string {
	if o == nil {
		return nil
	}
	return o.Coupon
}

func (o *GetDesignResDesignTokens) GetCustomCSS() *string {
	if o == nil {
		return nil
	}
	return o.CustomCSS
}

type GetDesignResUser struct {
	Emailaddress *string `json:"emailaddress,omitempty"`
	Fullname     *string `json:"fullname,omitempty"`
	Name         *string `json:"name,omitempty"`
	Userid       *string `json:"userid,omitempty"`
}

func (o *GetDesignResUser) GetEmailaddress() *string {
	if o == nil {
		return nil
	}
	return o.Emailaddress
}

func (o *GetDesignResUser) GetFullname() *string {
	if o == nil {
		return nil
	}
	return o.Fullname
}

func (o *GetDesignResUser) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GetDesignResUser) GetUserid() *string {
	if o == nil {
		return nil
	}
	return o.Userid
}

type GetDesignResDesign struct {
	BrandID   any     `json:"brand_id,omitempty"`
	BrandName *string `json:"brand_name,omitempty"`
	// Creation date and time
	CreatedAt      *string                   `json:"created_at,omitempty"`
	CreatedBy      *string                   `json:"created_by,omitempty"`
	CustomTheme    *string                   `json:"custom_theme,omitempty"`
	DesignTokens   *GetDesignResDesignTokens `json:"design_tokens,omitempty"`
	Edited         bool                      `json:"edited"`
	ID             *string                   `json:"id,omitempty"`
	IsDefault      *bool                     `json:"is_default,omitempty"`
	LastModifiedAt *string                   `json:"last_modified_at,omitempty"`
	Style          any                       `json:"style"`
	StyleName      string                    `json:"style_name"`
	UseCustomTheme *bool                     `json:"use_custom_theme,omitempty"`
	User           *GetDesignResUser         `json:"user,omitempty"`
}

func (o *GetDesignResDesign) GetBrandID() any {
	if o == nil {
		return nil
	}
	return o.BrandID
}

func (o *GetDesignResDesign) GetBrandName() *string {
	if o == nil {
		return nil
	}
	return o.BrandName
}

func (o *GetDesignResDesign) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *GetDesignResDesign) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *GetDesignResDesign) GetCustomTheme() *string {
	if o == nil {
		return nil
	}
	return o.CustomTheme
}

func (o *GetDesignResDesign) GetDesignTokens() *GetDesignResDesignTokens {
	if o == nil {
		return nil
	}
	return o.DesignTokens
}

func (o *GetDesignResDesign) GetEdited() bool {
	if o == nil {
		return false
	}
	return o.Edited
}

func (o *GetDesignResDesign) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *GetDesignResDesign) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

func (o *GetDesignResDesign) GetLastModifiedAt() *string {
	if o == nil {
		return nil
	}
	return o.LastModifiedAt
}

func (o *GetDesignResDesign) GetStyle() any {
	if o == nil {
		return nil
	}
	return o.Style
}

func (o *GetDesignResDesign) GetStyleName() string {
	if o == nil {
		return ""
	}
	return o.StyleName
}

func (o *GetDesignResDesign) GetUseCustomTheme() *bool {
	if o == nil {
		return nil
	}
	return o.UseCustomTheme
}

func (o *GetDesignResDesign) GetUser() *GetDesignResUser {
	if o == nil {
		return nil
	}
	return o.User
}

type GetDesignRes struct {
	Design *GetDesignResDesign `json:"design,omitempty"`
}

func (o *GetDesignRes) GetDesign() *GetDesignResDesign {
	if o == nil {
		return nil
	}
	return o.Design
}
