// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LogoData struct {
	Main *FileData `json:"main,omitempty"`
}

func (o *LogoData) GetMain() *FileData {
	if o == nil {
		return nil
	}
	return o.Main
}
