// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type LogoData struct {
	Main *FileData `json:"main,omitempty"`
}

func (l *LogoData) GetMain() *FileData {
	if l == nil {
		return nil
	}
	return l.Main
}
