// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PaletteData struct {
	Background            string  `json:"background"`
	Error                 string  `json:"error"`
	Navbar                string  `json:"navbar"`
	Paper                 string  `json:"paper"`
	PortalLoginBackground *string `json:"portal_login_background,omitempty"`
	Primary               string  `json:"primary"`
	Secondary             string  `json:"secondary"`
}

func (p *PaletteData) GetBackground() string {
	if p == nil {
		return ""
	}
	return p.Background
}

func (p *PaletteData) GetError() string {
	if p == nil {
		return ""
	}
	return p.Error
}

func (p *PaletteData) GetNavbar() string {
	if p == nil {
		return ""
	}
	return p.Navbar
}

func (p *PaletteData) GetPaper() string {
	if p == nil {
		return ""
	}
	return p.Paper
}

func (p *PaletteData) GetPortalLoginBackground() *string {
	if p == nil {
		return nil
	}
	return p.PortalLoginBackground
}

func (p *PaletteData) GetPrimary() string {
	if p == nil {
		return ""
	}
	return p.Primary
}

func (p *PaletteData) GetSecondary() string {
	if p == nil {
		return ""
	}
	return p.Secondary
}
