// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RemoveConsumerReq struct {
	// Id of the design
	ConsumerID string `json:"consumer_id"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ShouldDelete *string `json:"should_delete,omitempty"`
}

func (r *RemoveConsumerReq) GetConsumerID() string {
	if r == nil {
		return ""
	}
	return r.ConsumerID
}

func (r *RemoveConsumerReq) GetShouldDelete() *string {
	if r == nil {
		return nil
	}
	return r.ShouldDelete
}
