// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type Security struct {
	CustomAuthorizer string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *Security) GetCustomAuthorizer() string {
	if o == nil {
		return ""
	}
	return o.CustomAuthorizer
}
