// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TypographyData struct {
	Font      FontData `json:"font"`
	Primary   string   `json:"primary"`
	Secondary string   `json:"secondary"`
}

func (o *TypographyData) GetFont() FontData {
	if o == nil {
		return FontData{}
	}
	return o.Font
}

func (o *TypographyData) GetPrimary() string {
	if o == nil {
		return ""
	}
	return o.Primary
}

func (o *TypographyData) GetSecondary() string {
	if o == nil {
		return ""
	}
	return o.Secondary
}
