// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateDesignReqDesignTokens struct {
	Cashback  *string `json:"cashback,omitempty"`
	Coupon    *string `json:"coupon,omitempty"`
	CustomCSS *string `json:"custom_css,omitempty"`
}

func (u *UpdateDesignReqDesignTokens) GetCashback() *string {
	if u == nil {
		return nil
	}
	return u.Cashback
}

func (u *UpdateDesignReqDesignTokens) GetCoupon() *string {
	if u == nil {
		return nil
	}
	return u.Coupon
}

func (u *UpdateDesignReqDesignTokens) GetCustomCSS() *string {
	if u == nil {
		return nil
	}
	return u.CustomCSS
}

type UpdateDesignReqUser struct {
	Emailaddress *string `json:"emailaddress,omitempty"`
	Fullname     *string `json:"fullname,omitempty"`
	Name         *string `json:"name,omitempty"`
	Userid       *string `json:"userid,omitempty"`
}

func (u *UpdateDesignReqUser) GetEmailaddress() *string {
	if u == nil {
		return nil
	}
	return u.Emailaddress
}

func (u *UpdateDesignReqUser) GetFullname() *string {
	if u == nil {
		return nil
	}
	return u.Fullname
}

func (u *UpdateDesignReqUser) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateDesignReqUser) GetUserid() *string {
	if u == nil {
		return nil
	}
	return u.Userid
}

type UpdateDesignReqDesign struct {
	BrandID        any                          `json:"brand_id,omitempty"`
	BrandName      *string                      `json:"brand_name,omitempty"`
	CustomTheme    any                          `json:"custom_theme,omitempty"`
	DesignTokens   *UpdateDesignReqDesignTokens `json:"design_tokens,omitempty"`
	IsDefault      *bool                        `json:"is_default,omitempty"`
	Style          any                          `json:"style"`
	StyleName      string                       `json:"style_name"`
	UseCustomTheme *bool                        `json:"use_custom_theme,omitempty"`
	User           *UpdateDesignReqUser         `json:"user,omitempty"`
}

func (u *UpdateDesignReqDesign) GetBrandID() any {
	if u == nil {
		return nil
	}
	return u.BrandID
}

func (u *UpdateDesignReqDesign) GetBrandName() *string {
	if u == nil {
		return nil
	}
	return u.BrandName
}

func (u *UpdateDesignReqDesign) GetCustomTheme() any {
	if u == nil {
		return nil
	}
	return u.CustomTheme
}

func (u *UpdateDesignReqDesign) GetDesignTokens() *UpdateDesignReqDesignTokens {
	if u == nil {
		return nil
	}
	return u.DesignTokens
}

func (u *UpdateDesignReqDesign) GetIsDefault() *bool {
	if u == nil {
		return nil
	}
	return u.IsDefault
}

func (u *UpdateDesignReqDesign) GetStyle() any {
	if u == nil {
		return nil
	}
	return u.Style
}

func (u *UpdateDesignReqDesign) GetStyleName() string {
	if u == nil {
		return ""
	}
	return u.StyleName
}

func (u *UpdateDesignReqDesign) GetUseCustomTheme() *bool {
	if u == nil {
		return nil
	}
	return u.UseCustomTheme
}

func (u *UpdateDesignReqDesign) GetUser() *UpdateDesignReqUser {
	if u == nil {
		return nil
	}
	return u.User
}

type UpdateDesignReq struct {
	Design UpdateDesignReqDesign `json:"design"`
}

func (u *UpdateDesignReq) GetDesign() UpdateDesignReqDesign {
	if u == nil {
		return UpdateDesignReqDesign{}
	}
	return u.Design
}
