// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type UploadFileReqFileType string

const (
	UploadFileReqFileTypeLogo UploadFileReqFileType = "LOGO"
	UploadFileReqFileTypeFont UploadFileReqFileType = "FONT"
)

func (e UploadFileReqFileType) ToPointer() *UploadFileReqFileType {
	return &e
}
func (e *UploadFileReqFileType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "LOGO":
		fallthrough
	case "FONT":
		*e = UploadFileReqFileType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UploadFileReqFileType: %v", v)
	}
}

type UploadFileReq struct {
	DisplayName *string               `multipartForm:"name=display_name"`
	FileData    string                `multipartForm:"name=file_data"`
	FileName    string                `multipartForm:"name=file_name"`
	FileType    UploadFileReqFileType `multipartForm:"name=file_type"`
}

func (u *UploadFileReq) GetDisplayName() *string {
	if u == nil {
		return nil
	}
	return u.DisplayName
}

func (u *UploadFileReq) GetFileData() string {
	if u == nil {
		return ""
	}
	return u.FileData
}

func (u *UploadFileReq) GetFileName() string {
	if u == nil {
		return ""
	}
	return u.FileName
}

func (u *UploadFileReq) GetFileType() UploadFileReqFileType {
	if u == nil {
		return UploadFileReqFileType("")
	}
	return u.FileType
}
