// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type UploadFileResFileType string

const (
	UploadFileResFileTypeLogo  UploadFileResFileType = "LOGO"
	UploadFileResFileTypeFont  UploadFileResFileType = "FONT"
	UploadFileResFileTypeImage UploadFileResFileType = "IMAGE"
)

func (e UploadFileResFileType) ToPointer() *UploadFileResFileType {
	return &e
}
func (e *UploadFileResFileType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "LOGO":
		fallthrough
	case "FONT":
		fallthrough
	case "IMAGE":
		*e = UploadFileResFileType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UploadFileResFileType: %v", v)
	}
}

type UploadFileRes struct {
	DisplayName *string                `json:"display_name,omitempty"`
	FileType    *UploadFileResFileType `json:"file_type,omitempty"`
	Name        string                 `json:"name"`
	S3ObjectKey string                 `json:"s3_object_key"`
	URL         string                 `json:"url"`
}

func (u *UploadFileRes) GetDisplayName() *string {
	if u == nil {
		return nil
	}
	return u.DisplayName
}

func (u *UploadFileRes) GetFileType() *UploadFileResFileType {
	if u == nil {
		return nil
	}
	return u.FileType
}

func (u *UploadFileRes) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UploadFileRes) GetS3ObjectKey() string {
	if u == nil {
		return ""
	}
	return u.S3ObjectKey
}

func (u *UploadFileRes) GetURL() string {
	if u == nil {
		return ""
	}
	return u.URL
}
