// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type WidgetPortalData struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (o *WidgetPortalData) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *WidgetPortalData) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
