workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://docs.api.epilot.io/design-builder-api.yaml
targets:
    terraform:
        target: terraform
        source: my-source
