// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *DesignDataSourceModel) RefreshFromSharedGetDesignRes(ctx context.Context, resp *shared.GetDesignRes) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedGetDesignResDesign(ctx, resp.Design)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *DesignDataSourceModel) RefreshFromSharedGetDesignResDesign(ctx context.Context, resp *shared.GetDesignResDesign) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Manifest = make([]types.String, 0, len(resp.Manifest))
		for _, v := range resp.Manifest {
			r.Manifest = append(r.Manifest, types.StringValue(v))
		}
		if resp.BrandID == nil {
			r.BrandID = jsontypes.NewNormalizedNull()
		} else {
			brandIDResult, _ := json.Marshal(resp.BrandID)
			r.BrandID = jsontypes.NewNormalizedValue(string(brandIDResult))
		}
		r.BrandName = types.StringPointerValue(resp.BrandName)
		r.CreatedAt = types.StringPointerValue(resp.CreatedAt)
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		if resp.CustomTheme == nil {
			r.CustomTheme = jsontypes.NewNormalizedNull()
		} else {
			customThemeResult, _ := json.Marshal(resp.CustomTheme)
			r.CustomTheme = jsontypes.NewNormalizedValue(string(customThemeResult))
		}
		if resp.DesignTokens == nil {
			r.DesignTokens = nil
		} else {
			r.DesignTokens = &tfTypes.DesignTokens{}
			r.DesignTokens.AccentColor = types.StringPointerValue(resp.DesignTokens.AccentColor)
			r.DesignTokens.ButtonBorderRadius = types.Float64PointerValue(resp.DesignTokens.ButtonBorderRadius)
			r.DesignTokens.ButtonGhostBg = types.StringPointerValue(resp.DesignTokens.ButtonGhostBg)
			r.DesignTokens.ButtonGhostHoverBg = types.StringPointerValue(resp.DesignTokens.ButtonGhostHoverBg)
			r.DesignTokens.ButtonGhostHoverText = types.StringPointerValue(resp.DesignTokens.ButtonGhostHoverText)
			r.DesignTokens.ButtonGhostText = types.StringPointerValue(resp.DesignTokens.ButtonGhostText)
			r.DesignTokens.ButtonHeight = types.Float64PointerValue(resp.DesignTokens.ButtonHeight)
			r.DesignTokens.ButtonOutlinedBorder = types.StringPointerValue(resp.DesignTokens.ButtonOutlinedBorder)
			r.DesignTokens.ButtonOutlinedHoverBg = types.StringPointerValue(resp.DesignTokens.ButtonOutlinedHoverBg)
			r.DesignTokens.ButtonOutlinedHoverText = types.StringPointerValue(resp.DesignTokens.ButtonOutlinedHoverText)
			r.DesignTokens.ButtonOutlinedText = types.StringPointerValue(resp.DesignTokens.ButtonOutlinedText)
			r.DesignTokens.ButtonPrimaryBg = types.StringPointerValue(resp.DesignTokens.ButtonPrimaryBg)
			r.DesignTokens.ButtonPrimaryHoverBg = types.StringPointerValue(resp.DesignTokens.ButtonPrimaryHoverBg)
			r.DesignTokens.ButtonPrimaryHoverText = types.StringPointerValue(resp.DesignTokens.ButtonPrimaryHoverText)
			r.DesignTokens.ButtonPrimaryText = types.StringPointerValue(resp.DesignTokens.ButtonPrimaryText)
			r.DesignTokens.CardBackground = types.StringPointerValue(resp.DesignTokens.CardBackground)
			r.DesignTokens.CardBorderColor = types.StringPointerValue(resp.DesignTokens.CardBorderColor)
			if resp.DesignTokens.CardVariant != nil {
				r.DesignTokens.CardVariant = types.StringValue(string(*resp.DesignTokens.CardVariant))
			} else {
				r.DesignTokens.CardVariant = types.StringNull()
			}
			r.DesignTokens.Cashback = types.StringPointerValue(resp.DesignTokens.Cashback)
			r.DesignTokens.CheckboxLabelColor = types.StringPointerValue(resp.DesignTokens.CheckboxLabelColor)
			r.DesignTokens.CheckboxUncheckedColor = types.StringPointerValue(resp.DesignTokens.CheckboxUncheckedColor)
			r.DesignTokens.ChipBackground = types.StringPointerValue(resp.DesignTokens.ChipBackground)
			r.DesignTokens.ChipHoverBackground = types.StringPointerValue(resp.DesignTokens.ChipHoverBackground)
			r.DesignTokens.ChipHoverTextColor = types.StringPointerValue(resp.DesignTokens.ChipHoverTextColor)
			r.DesignTokens.ChipTextColor = types.StringPointerValue(resp.DesignTokens.ChipTextColor)
			r.DesignTokens.Coupon = types.StringPointerValue(resp.DesignTokens.Coupon)
			r.DesignTokens.CustomCSS = types.StringPointerValue(resp.DesignTokens.CustomCSS)
			r.DesignTokens.DatepickerBorderRadius = types.Float64PointerValue(resp.DesignTokens.DatepickerBorderRadius)
			r.DesignTokens.DatepickerSelectedBg = types.StringPointerValue(resp.DesignTokens.DatepickerSelectedBg)
			r.DesignTokens.DatepickerSelectedColor = types.StringPointerValue(resp.DesignTokens.DatepickerSelectedColor)
			r.DesignTokens.DividerColor = types.StringPointerValue(resp.DesignTokens.DividerColor)
			r.DesignTokens.DropdownHoverBg = types.StringPointerValue(resp.DesignTokens.DropdownHoverBg)
			r.DesignTokens.DropdownHoverText = types.StringPointerValue(resp.DesignTokens.DropdownHoverText)
			r.DesignTokens.DropdownSelectedBg = types.StringPointerValue(resp.DesignTokens.DropdownSelectedBg)
			r.DesignTokens.DropdownSelectedText = types.StringPointerValue(resp.DesignTokens.DropdownSelectedText)
			if resp.DesignTokens.FontSizeScale != nil {
				r.DesignTokens.FontSizeScale = types.StringValue(string(*resp.DesignTokens.FontSizeScale))
			} else {
				r.DesignTokens.FontSizeScale = types.StringNull()
			}
			r.DesignTokens.InputBackground = types.StringPointerValue(resp.DesignTokens.InputBackground)
			r.DesignTokens.InputBorderColor = types.StringPointerValue(resp.DesignTokens.InputBorderColor)
			r.DesignTokens.InputBorderRadius = types.Float64PointerValue(resp.DesignTokens.InputBorderRadius)
			r.DesignTokens.InputHeight = types.Float64PointerValue(resp.DesignTokens.InputHeight)
			r.DesignTokens.InputLabelColor = types.StringPointerValue(resp.DesignTokens.InputLabelColor)
			r.DesignTokens.InputTextColor = types.StringPointerValue(resp.DesignTokens.InputTextColor)
			if resp.DesignTokens.InputVariant != nil {
				r.DesignTokens.InputVariant = types.StringValue(string(*resp.DesignTokens.InputVariant))
			} else {
				r.DesignTokens.InputVariant = types.StringNull()
			}
			r.DesignTokens.LinkColor = types.StringPointerValue(resp.DesignTokens.LinkColor)
			r.DesignTokens.LinkHoverColor = types.StringPointerValue(resp.DesignTokens.LinkHoverColor)
			r.DesignTokens.LogoSize = types.Float64PointerValue(resp.DesignTokens.LogoSize)
			r.DesignTokens.OutlineColor = types.StringPointerValue(resp.DesignTokens.OutlineColor)
			r.DesignTokens.RadioLabelColor = types.StringPointerValue(resp.DesignTokens.RadioLabelColor)
			r.DesignTokens.RadioUncheckedColor = types.StringPointerValue(resp.DesignTokens.RadioUncheckedColor)
			r.DesignTokens.SummaryCardBackground = types.StringPointerValue(resp.DesignTokens.SummaryCardBackground)
			r.DesignTokens.SwitchBorderRadius = types.Float64PointerValue(resp.DesignTokens.SwitchBorderRadius)
			r.DesignTokens.SwitchUncheckedBg = types.StringPointerValue(resp.DesignTokens.SwitchUncheckedBg)
			r.DesignTokens.SwitchUncheckedColor = types.StringPointerValue(resp.DesignTokens.SwitchUncheckedColor)
			r.DesignTokens.ToggleBorderColor = types.StringPointerValue(resp.DesignTokens.ToggleBorderColor)
			r.DesignTokens.ToggleHoverBg = types.StringPointerValue(resp.DesignTokens.ToggleHoverBg)
			r.DesignTokens.ToggleHoverText = types.StringPointerValue(resp.DesignTokens.ToggleHoverText)
			r.DesignTokens.ToggleSelectedBg = types.StringPointerValue(resp.DesignTokens.ToggleSelectedBg)
			r.DesignTokens.ToggleSelectedText = types.StringPointerValue(resp.DesignTokens.ToggleSelectedText)
			r.DesignTokens.TopbarHeight = types.Float64PointerValue(resp.DesignTokens.TopbarHeight)
			if resp.DesignTokens.TopbarLogoAlignment != nil {
				r.DesignTokens.TopbarLogoAlignment = types.StringValue(string(*resp.DesignTokens.TopbarLogoAlignment))
			} else {
				r.DesignTokens.TopbarLogoAlignment = types.StringNull()
			}
		}
		r.Edited = types.BoolValue(resp.Edited)
		r.ID = types.StringPointerValue(resp.ID)
		r.IsDefault = types.BoolPointerValue(resp.IsDefault)
		r.LastModifiedAt = types.StringPointerValue(resp.LastModifiedAt)
		styleResult, _ := json.Marshal(resp.Style)
		r.Style = jsontypes.NewNormalizedValue(string(styleResult))
		r.StyleName = types.StringValue(resp.StyleName)
		r.UseCustomTheme = types.BoolPointerValue(resp.UseCustomTheme)
		if resp.User == nil {
			r.User = nil
		} else {
			r.User = &tfTypes.User{}
			r.User.Emailaddress = types.StringPointerValue(resp.User.Emailaddress)
			r.User.Fullname = types.StringPointerValue(resp.User.Fullname)
			r.User.Name = types.StringPointerValue(resp.User.Name)
			r.User.Userid = types.StringPointerValue(resp.User.Userid)
		}
	}

	return diags
}

func (r *DesignDataSourceModel) ToOperationsGetDesignRequest(ctx context.Context) (*operations.GetDesignRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var designID string
	designID = r.ID.ValueString()

	out := operations.GetDesignRequest{
		DesignID: designID,
	}

	return &out, diags
}
