// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *DesignDataSourceModel) RefreshFromSharedGetDesignRes(ctx context.Context, resp *shared.GetDesignRes) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedGetDesignResDesign(ctx, resp.Design)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *DesignDataSourceModel) RefreshFromSharedGetDesignResDesign(ctx context.Context, resp *shared.GetDesignResDesign) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.BrandID == nil {
			r.BrandID = jsontypes.NewNormalizedNull()
		} else {
			brandIDResult, _ := json.Marshal(resp.BrandID)
			r.BrandID = jsontypes.NewNormalizedValue(string(brandIDResult))
		}
		r.BrandName = types.StringPointerValue(resp.BrandName)
		r.CreatedAt = types.StringPointerValue(resp.CreatedAt)
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		if resp.CustomTheme == nil {
			r.CustomTheme = jsontypes.NewNormalizedNull()
		} else {
			customThemeResult, _ := json.Marshal(resp.CustomTheme)
			r.CustomTheme = jsontypes.NewNormalizedValue(string(customThemeResult))
		}
		if resp.DesignTokens == nil {
			r.DesignTokens = nil
		} else {
			r.DesignTokens = &tfTypes.DesignTokens{}
			r.DesignTokens.Cashback = types.StringPointerValue(resp.DesignTokens.Cashback)
			r.DesignTokens.Coupon = types.StringPointerValue(resp.DesignTokens.Coupon)
			r.DesignTokens.CustomCSS = types.StringPointerValue(resp.DesignTokens.CustomCSS)
		}
		r.Edited = types.BoolValue(resp.Edited)
		r.ID = types.StringPointerValue(resp.ID)
		r.IsDefault = types.BoolPointerValue(resp.IsDefault)
		r.LastModifiedAt = types.StringPointerValue(resp.LastModifiedAt)
		styleResult, _ := json.Marshal(resp.Style)
		r.Style = jsontypes.NewNormalizedValue(string(styleResult))
		r.StyleName = types.StringValue(resp.StyleName)
		r.UseCustomTheme = types.BoolPointerValue(resp.UseCustomTheme)
		if resp.User == nil {
			r.User = nil
		} else {
			r.User = &tfTypes.User{}
			r.User.Emailaddress = types.StringPointerValue(resp.User.Emailaddress)
			r.User.Fullname = types.StringPointerValue(resp.User.Fullname)
			r.User.Name = types.StringPointerValue(resp.User.Name)
			r.User.Userid = types.StringPointerValue(resp.User.Userid)
		}
	}

	return diags
}

func (r *DesignDataSourceModel) ToOperationsGetDesignRequest(ctx context.Context) (*operations.GetDesignRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var designID string
	designID = r.ID.ValueString()

	out := operations.GetDesignRequest{
		DesignID: designID,
	}

	return &out, diags
}
