// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-designbuilder/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *DesignResourceModel) RefreshFromSharedAddDesignRes(resp *shared.AddDesignRes) {
	if resp.Design == nil {
		r.Design = nil
	} else {
		r.Design = &AddDesignResDesign{}
		r.Design.BrandID = types.StringPointerValue(resp.Design.BrandID)
		r.Design.BrandName = types.StringPointerValue(resp.Design.BrandName)
		if resp.Design.CreatedAt != nil {
			r.Design.CreatedAt = types.StringValue(resp.Design.CreatedAt.Format(time.RFC3339Nano))
		} else {
			r.Design.CreatedAt = types.StringNull()
		}
		r.Design.CreatedBy = types.StringPointerValue(resp.Design.CreatedBy)
		r.Design.CustomTheme = types.StringPointerValue(resp.Design.CustomTheme)
		r.Design.Edited = types.BoolValue(resp.Design.Edited)
		r.Design.ID = types.StringPointerValue(resp.Design.ID)
		if resp.Design.LastModifiedAt != nil {
			r.Design.LastModifiedAt = types.StringValue(resp.Design.LastModifiedAt.Format(time.RFC3339Nano))
		} else {
			r.Design.LastModifiedAt = types.StringNull()
		}
		r.Design.Style.Consumer.CustomerPortals = nil
		for _, customerPortalsItem := range resp.Design.Style.Consumer.CustomerPortals {
			var customerPortals1 types.String
			customerPortals1Result, _ := json.Marshal(customerPortalsItem)
			customerPortals1 = types.StringValue(string(customerPortals1Result))
			r.Design.Style.Consumer.CustomerPortals = append(r.Design.Style.Consumer.CustomerPortals, customerPortals1)
		}
		r.Design.Style.Consumer.Widgets = nil
		for _, widgetsItem := range resp.Design.Style.Consumer.Widgets {
			var widgets1 types.String
			widgets1Result, _ := json.Marshal(widgetsItem)
			widgets1 = types.StringValue(string(widgets1Result))
			r.Design.Style.Consumer.Widgets = append(r.Design.Style.Consumer.Widgets, widgets1)
		}
		if resp.Design.Style.Logo == nil {
			r.Design.Style.Logo = nil
		} else {
			r.Design.Style.Logo = &LogoData{}
			if resp.Design.Style.Logo.Main == nil {
				r.Design.Style.Logo.Main = nil
			} else {
				r.Design.Style.Logo.Main = &FileData{}
				r.Design.Style.Logo.Main.DisplayName = types.StringPointerValue(resp.Design.Style.Logo.Main.DisplayName)
				if resp.Design.Style.Logo.Main.FileType != nil {
					r.Design.Style.Logo.Main.FileType = types.StringValue(string(*resp.Design.Style.Logo.Main.FileType))
				} else {
					r.Design.Style.Logo.Main.FileType = types.StringNull()
				}
				r.Design.Style.Logo.Main.Name = types.StringValue(resp.Design.Style.Logo.Main.Name)
				r.Design.Style.Logo.Main.S3ObjectKey = types.StringValue(resp.Design.Style.Logo.Main.S3ObjectKey)
				r.Design.Style.Logo.Main.URL = types.StringValue(resp.Design.Style.Logo.Main.URL)
			}
		}
		r.Design.Style.Palette.Background = types.StringValue(resp.Design.Style.Palette.Background)
		r.Design.Style.Palette.Error = types.StringValue(resp.Design.Style.Palette.Error)
		r.Design.Style.Palette.Navbar = types.StringValue(resp.Design.Style.Palette.Navbar)
		r.Design.Style.Palette.Paper = types.StringValue(resp.Design.Style.Palette.Paper)
		r.Design.Style.Palette.Primary = types.StringValue(resp.Design.Style.Palette.Primary)
		r.Design.Style.Palette.Secondary = types.StringValue(resp.Design.Style.Palette.Secondary)
		r.Design.Style.Typography.Font.FontFamily = types.StringPointerValue(resp.Design.Style.Typography.Font.FontFamily)
		r.Design.Style.Typography.Font.FontID = types.StringValue(resp.Design.Style.Typography.Font.FontID)
		r.Design.Style.Typography.Font.FontName = types.StringValue(resp.Design.Style.Typography.Font.FontName)
		r.Design.Style.Typography.Font.FontWeightBold = types.StringPointerValue(resp.Design.Style.Typography.Font.FontWeightBold)
		r.Design.Style.Typography.Font.FontWeightMedium = types.StringPointerValue(resp.Design.Style.Typography.Font.FontWeightMedium)
		r.Design.Style.Typography.Font.FontWeightRegular = types.StringPointerValue(resp.Design.Style.Typography.Font.FontWeightRegular)
		r.Design.Style.Typography.Font.Urls = nil
		for _, urlsItem := range resp.Design.Style.Typography.Font.Urls {
			var urls1 types.String
			urls1Result, _ := json.Marshal(urlsItem)
			urls1 = types.StringValue(string(urls1Result))
			r.Design.Style.Typography.Font.Urls = append(r.Design.Style.Typography.Font.Urls, urls1)
		}
		r.Design.Style.Typography.Primary = types.StringValue(resp.Design.Style.Typography.Primary)
		r.Design.Style.Typography.Secondary = types.StringValue(resp.Design.Style.Typography.Secondary)
		r.Design.StyleName = types.StringValue(resp.Design.StyleName)
		r.Design.UseCustomTheme = types.BoolPointerValue(resp.Design.UseCustomTheme)
		if resp.Design.User == nil {
			r.Design.User = nil
		} else {
			r.Design.User = &AddDesignResUser{}
			r.Design.User.Emailaddress = types.StringPointerValue(resp.Design.User.Emailaddress)
			r.Design.User.Fullname = types.StringPointerValue(resp.Design.User.Fullname)
			r.Design.User.Name = types.StringPointerValue(resp.Design.User.Name)
			r.Design.User.Userid = types.StringPointerValue(resp.Design.User.Userid)
		}
	}
}

func (r *DesignResourceModel) ToSharedUpdateDesignReq() *shared.UpdateDesignReq {
	brandID := new(string)
	if !r.Design.BrandID.IsUnknown() && !r.Design.BrandID.IsNull() {
		*brandID = r.Design.BrandID.ValueString()
	} else {
		brandID = nil
	}
	brandName := new(string)
	if !r.Design.BrandName.IsUnknown() && !r.Design.BrandName.IsNull() {
		*brandName = r.Design.BrandName.ValueString()
	} else {
		brandName = nil
	}
	customTheme := new(string)
	if !r.Design.CustomTheme.IsUnknown() && !r.Design.CustomTheme.IsNull() {
		*customTheme = r.Design.CustomTheme.ValueString()
	} else {
		customTheme = nil
	}
	var customerPortals []interface{} = nil
	for _, customerPortalsItem := range r.Design.Style.Consumer.CustomerPortals {
		var customerPortalsTmp interface{}
		_ = json.Unmarshal([]byte(customerPortalsItem.ValueString()), &customerPortalsTmp)
		customerPortals = append(customerPortals, customerPortalsTmp)
	}
	var widgets []interface{} = nil
	for _, widgetsItem := range r.Design.Style.Consumer.Widgets {
		var widgetsTmp interface{}
		_ = json.Unmarshal([]byte(widgetsItem.ValueString()), &widgetsTmp)
		widgets = append(widgets, widgetsTmp)
	}
	consumer := shared.ConsumerData{
		CustomerPortals: customerPortals,
		Widgets:         widgets,
	}
	var logo *shared.LogoData
	if r.Design.Style.Logo != nil {
		var main *shared.FileData
		if r.Design.Style.Logo.Main != nil {
			displayName := new(string)
			if !r.Design.Style.Logo.Main.DisplayName.IsUnknown() && !r.Design.Style.Logo.Main.DisplayName.IsNull() {
				*displayName = r.Design.Style.Logo.Main.DisplayName.ValueString()
			} else {
				displayName = nil
			}
			fileType := new(shared.FileType)
			if !r.Design.Style.Logo.Main.FileType.IsUnknown() && !r.Design.Style.Logo.Main.FileType.IsNull() {
				*fileType = shared.FileType(r.Design.Style.Logo.Main.FileType.ValueString())
			} else {
				fileType = nil
			}
			name := r.Design.Style.Logo.Main.Name.ValueString()
			s3ObjectKey := r.Design.Style.Logo.Main.S3ObjectKey.ValueString()
			url := r.Design.Style.Logo.Main.URL.ValueString()
			main = &shared.FileData{
				DisplayName: displayName,
				FileType:    fileType,
				Name:        name,
				S3ObjectKey: s3ObjectKey,
				URL:         url,
			}
		}
		logo = &shared.LogoData{
			Main: main,
		}
	}
	background := r.Design.Style.Palette.Background.ValueString()
	error := r.Design.Style.Palette.Error.ValueString()
	navbar := r.Design.Style.Palette.Navbar.ValueString()
	paper := r.Design.Style.Palette.Paper.ValueString()
	primary := r.Design.Style.Palette.Primary.ValueString()
	secondary := r.Design.Style.Palette.Secondary.ValueString()
	palette := shared.PaletteData{
		Background: background,
		Error:      error,
		Navbar:     navbar,
		Paper:      paper,
		Primary:    primary,
		Secondary:  secondary,
	}
	fontFamily := new(string)
	if !r.Design.Style.Typography.Font.FontFamily.IsUnknown() && !r.Design.Style.Typography.Font.FontFamily.IsNull() {
		*fontFamily = r.Design.Style.Typography.Font.FontFamily.ValueString()
	} else {
		fontFamily = nil
	}
	fontID := r.Design.Style.Typography.Font.FontID.ValueString()
	fontName := r.Design.Style.Typography.Font.FontName.ValueString()
	fontWeightBold := new(string)
	if !r.Design.Style.Typography.Font.FontWeightBold.IsUnknown() && !r.Design.Style.Typography.Font.FontWeightBold.IsNull() {
		*fontWeightBold = r.Design.Style.Typography.Font.FontWeightBold.ValueString()
	} else {
		fontWeightBold = nil
	}
	fontWeightMedium := new(string)
	if !r.Design.Style.Typography.Font.FontWeightMedium.IsUnknown() && !r.Design.Style.Typography.Font.FontWeightMedium.IsNull() {
		*fontWeightMedium = r.Design.Style.Typography.Font.FontWeightMedium.ValueString()
	} else {
		fontWeightMedium = nil
	}
	fontWeightRegular := new(string)
	if !r.Design.Style.Typography.Font.FontWeightRegular.IsUnknown() && !r.Design.Style.Typography.Font.FontWeightRegular.IsNull() {
		*fontWeightRegular = r.Design.Style.Typography.Font.FontWeightRegular.ValueString()
	} else {
		fontWeightRegular = nil
	}
	var urls []interface{} = nil
	for _, urlsItem := range r.Design.Style.Typography.Font.Urls {
		var urlsTmp interface{}
		_ = json.Unmarshal([]byte(urlsItem.ValueString()), &urlsTmp)
		urls = append(urls, urlsTmp)
	}
	font := shared.FontData{
		FontFamily:        fontFamily,
		FontID:            fontID,
		FontName:          fontName,
		FontWeightBold:    fontWeightBold,
		FontWeightMedium:  fontWeightMedium,
		FontWeightRegular: fontWeightRegular,
		Urls:              urls,
	}
	primary1 := r.Design.Style.Typography.Primary.ValueString()
	secondary1 := r.Design.Style.Typography.Secondary.ValueString()
	typography := shared.TypographyData{
		Font:      font,
		Primary:   primary1,
		Secondary: secondary1,
	}
	style := shared.UpdateDesignReqStyle{
		Consumer:   consumer,
		Logo:       logo,
		Palette:    palette,
		Typography: typography,
	}
	styleName := r.Design.StyleName.ValueString()
	useCustomTheme := new(bool)
	if !r.Design.UseCustomTheme.IsUnknown() && !r.Design.UseCustomTheme.IsNull() {
		*useCustomTheme = r.Design.UseCustomTheme.ValueBool()
	} else {
		useCustomTheme = nil
	}
	var user *shared.UpdateDesignReqUser
	if r.Design.User != nil {
		emailaddress := new(string)
		if !r.Design.User.Emailaddress.IsUnknown() && !r.Design.User.Emailaddress.IsNull() {
			*emailaddress = r.Design.User.Emailaddress.ValueString()
		} else {
			emailaddress = nil
		}
		fullname := new(string)
		if !r.Design.User.Fullname.IsUnknown() && !r.Design.User.Fullname.IsNull() {
			*fullname = r.Design.User.Fullname.ValueString()
		} else {
			fullname = nil
		}
		name1 := new(string)
		if !r.Design.User.Name.IsUnknown() && !r.Design.User.Name.IsNull() {
			*name1 = r.Design.User.Name.ValueString()
		} else {
			name1 = nil
		}
		userid := new(string)
		if !r.Design.User.Userid.IsUnknown() && !r.Design.User.Userid.IsNull() {
			*userid = r.Design.User.Userid.ValueString()
		} else {
			userid = nil
		}
		user = &shared.UpdateDesignReqUser{
			Emailaddress: emailaddress,
			Fullname:     fullname,
			Name:         name1,
			Userid:       userid,
		}
	}
	design := shared.UpdateDesignReqDesign{
		BrandID:        brandID,
		BrandName:      brandName,
		CustomTheme:    customTheme,
		Style:          style,
		StyleName:      styleName,
		UseCustomTheme: useCustomTheme,
		User:           user,
	}
	out := shared.UpdateDesignReq{
		Design: design,
	}
	return &out
}
