// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type GetDesignResDesign struct {
	BrandID        *BrandID          `tfsdk:"brand_id"`
	BrandName      types.String      `tfsdk:"brand_name"`
	CreatedAt      types.String      `tfsdk:"created_at"`
	CreatedBy      types.String      `tfsdk:"created_by"`
	CustomTheme    *CustomTheme      `tfsdk:"custom_theme"`
	Edited         types.Bool        `tfsdk:"edited"`
	ID             types.String      `tfsdk:"id"`
	LastModifiedAt types.String      `tfsdk:"last_modified_at"`
	Style          GetDesignResStyle `tfsdk:"style"`
	StyleName      types.String      `tfsdk:"style_name"`
	UseCustomTheme types.Bool        `tfsdk:"use_custom_theme"`
	User           *GetDesignResUser `tfsdk:"user"`
}
