// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ConsumerData struct {
	CustomerPortals []types.String `tfsdk:"customer_portals"`
	Widgets         []types.String `tfsdk:"widgets"`
}
