// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type Style struct {
	Consumer   ConsumerData   `tfsdk:"consumer"`
	Logo       *LogoData      `tfsdk:"logo"`
	Palette    PaletteData    `tfsdk:"palette"`
	Typography TypographyData `tfsdk:"typography"`
}
