// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type BrandID struct {
	Str    types.String `tfsdk:"str"`
	Number types.Number `tfsdk:"number"`
}
