// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type JourneyCreationRequestRules struct {
	Source     types.String `tfsdk:"source"`
	SourceType types.String `tfsdk:"source_type"`
	Target     types.String `tfsdk:"target"`
	Type       types.String `tfsdk:"type"`
}
