// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type AddDesignResDesign struct {
	BrandID        types.String      `tfsdk:"brand_id"`
	BrandName      types.String      `tfsdk:"brand_name"`
	CreatedAt      types.String      `tfsdk:"created_at"`
	CreatedBy      types.String      `tfsdk:"created_by"`
	CustomTheme    types.String      `tfsdk:"custom_theme"`
	Edited         types.Bool        `tfsdk:"edited"`
	ID             types.String      `tfsdk:"id"`
	LastModifiedAt types.String      `tfsdk:"last_modified_at"`
	Style          AddDesignResStyle `tfsdk:"style"`
	StyleName      types.String      `tfsdk:"style_name"`
	UseCustomTheme types.Bool        `tfsdk:"use_custom_theme"`
	User           *AddDesignResUser `tfsdk:"user"`
}
