// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type DesignTokens struct {
	Cashback  types.String `tfsdk:"cashback"`
	Coupon    types.String `tfsdk:"coupon"`
	CustomCSS types.String `tfsdk:"custom_css"`
}
