// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotjourney/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetJourneyRequest struct {
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Organization ID
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

type GetJourneyResponse struct {
	ContentType string
	// Success
	JourneyResponse *shared.JourneyResponse
	StatusCode      int
	RawResponse     *http.Response
}
