// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetJourneyV2Request struct {
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// What source ID. Journey or Entity ID
	Source *string `queryParam:"style=form,explode=true,name=source"`
}

func (o *GetJourneyV2Request) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetJourneyV2Request) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

type GetJourneyV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	Journey *shared.Journey
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetJourneyV2Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetJourneyV2Response) GetJourney() *shared.Journey {
	if o == nil {
		return nil
	}
	return o.Journey
}

func (o *GetJourneyV2Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetJourneyV2Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
