// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-journey/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetJourneyProductsRequest struct {
	// city for availibility
	City *string `queryParam:"style=form,explode=true,name=city"`
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Organization ID
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
	// Zip Code for availibility
	PostalCode *string `queryParam:"style=form,explode=true,name=postal_code"`
	// What source ID. Journey or Entity ID
	Source *string `queryParam:"style=form,explode=true,name=source"`
	// street name for availibility
	Street *string `queryParam:"style=form,explode=true,name=street"`
	// street number for availibility
	StreetNumber *string `queryParam:"style=form,explode=true,name=street_number"`
}

func (o *GetJourneyProductsRequest) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *GetJourneyProductsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetJourneyProductsRequest) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *GetJourneyProductsRequest) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *GetJourneyProductsRequest) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *GetJourneyProductsRequest) GetStreet() *string {
	if o == nil {
		return nil
	}
	return o.Street
}

func (o *GetJourneyProductsRequest) GetStreetNumber() *string {
	if o == nil {
		return nil
	}
	return o.StreetNumber
}

type GetJourneyProductsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	JourneyProductsResponse []shared.JourneyProductsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetJourneyProductsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetJourneyProductsResponse) GetJourneyProductsResponse() []shared.JourneyProductsResponse {
	if o == nil {
		return nil
	}
	return o.JourneyProductsResponse
}

func (o *GetJourneyProductsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetJourneyProductsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
