// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RemoveJourneyRequest struct {
	// Journey ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type RemoveJourneyResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
