// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilot-journey/internal/sdk/pkg/models/shared"
	"net/http"
)

type SearchJourneysResponse struct {
	ContentType string
	// Success
	SearchJourneysResponse *shared.SearchJourneysResponse
	StatusCode             int
	RawResponse            *http.Response
}
