// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotjourney/internal/sdk/pkg/models/shared"
	"net/http"
)

type SearchJourneysRequest struct {
	// Payload
	Request *shared.SearchJourneysQueryRequest `request:"mediaType=application/json"`
}

type SearchJourneysResponse struct {
	ContentType string
	// Success
	SearchJourneysResponse *shared.SearchJourneysResponse
	StatusCode             int
	RawResponse            *http.Response
}
