name: Autorelease

# on each main branch push, bump version and publish a release
"on":
  push:
    branches:
      - main

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - name: Set up Semantic Versioning
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          bump_type="patch" # Default bump type

          if git log $latest_tag..HEAD --oneline | grep "BREAKING CHANGE"; then
            bump_type="major"
          elif git log $latest_tag..HEAD --oneline | grep "feat:"; then
            bump_type="minor"
          fi

          new_version=$(semver $latest_tag $bump_type)
          echo "New version: $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
      - name: Create Tag
        run: |
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}
