name: Autorelease

# on each main branch push, bump version and publish a release
"on":
  push:
    branches:
      - main

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - name: Create tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
