name: Autorelease

# on each main branch push, bump version and publish a release
"on":
  push:
    branches:
      - main

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          skipInvalidTags: true
          noVersionBumpBehavior: patch
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          body: Update Terraform Provider with latest API changes
          token: ${{ secrets.GITHUB_TOKEN }}
